### ISSUE TITLE
Migrate transport.open.data to opentransportdata.swiss

### ISSUE THREAD

**Issue by nico6ka** [timeforcoffee/timeforcoffee-android#17]

**Comment by lucasardonini** [comment]
This can only be done in the backend and we can't make improvements on it. So maybe we should develop a new one ?

**Comment by chregu** [comment]
What do you mean with that? does that relate to http://tfc.chregu.tv/api or something else?

**Comment by lucasardonini** [comment]
Yes that's it. We can access the code but nobody in our team knows that language

**Comment by chregu** [comment]
Depending what you want to achieve, but rewriting it just to change to opentransportdata.swiss , not sure that's worth the effort. Especially also since transport.opendata.ch nowadays uses opentransportdata.swiss as backend anyway

Unfortunately my clojure knowledge is also very limited to do major changes on the current backend :( But works for me right now and bringing it on the same level in a rewrite will be quite effort (since it uses different backends, not only opentransportdata.swiss for more real time data, and merges them )

Just my 2 rappen ;)

**Comment by lucasardonini** [comment]
Ok I see. I didn't know that transport.opendata.ch is using opentransportdata.swiss. In that case, it makes no sens to migrate the app to opentransportdata.swiss...
