### ISSUE TITLE
"Network error" when clicking on some lines from certain "stations"

### ISSUE THREAD

**Issue by FriedrichIII** [timeforcoffee/timeforcoffee-android#64]
Example : 
From station Bern (whatever the station "Bern" is) -> "Bern Marzili", "Bern Guterbahnhof"
From station Zurich HB -> "Zurich, Frankental", Zurich WerdHolzli

See what's wrong with the API response in these cases.

**Comment by lucasardonini** [comment]
This is because of backend response. Some times, the list of checkpoints is returned like this:
<img width="843" alt="screen shot 2018-03-13 at 11 36 52" src="https://user-images.githubusercontent.com/13674665/37337278-0dea3fe0-26b4-11e8-868b-0d306ec67cb4.png">

And some times like this: 
<img width="815" alt="screen shot 2018-03-13 at 11 37 06" src="https://user-images.githubusercontent.com/13674665/37337303-1e966486-26b4-11e8-8c3c-f342b3c33840.png">

**Comment by FriedrichIII** [comment]
There's another case where we have the error. Everything looks fine, but there's a connection with no arrival :
[connections.txt](https://github.com/timeforcoffee/timeforcoffee-android/files/1815194/connections.txt)
